"""modify Column

Revision ID: 6cd18fa4f6b0
Revises: 6b1d43111d6c
Create Date: 2017-04-24 10:07:24.934000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cd18fa4f6b0'
down_revision = '6b1d43111d6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
