"""modify Column

Revision ID: b0dc82e5879f
Revises: 6cd18fa4f6b0
Create Date: 2017-04-24 11:42:51.696000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0dc82e5879f'
down_revision = '6cd18fa4f6b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
