"""empty message

Revision ID: b56c2604fec1
Revises: 
Create Date: 2017-05-10 22:41:05.839000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b56c2604fec1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('watched_videos_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'video', ['watched_videos_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'watched_videos_id')
    # ### end Alembic commands ###
