"""empty message

Revision ID: d7e5407726b7
Revises: 90478e1df358
Create Date: 2017-05-10 23:21:11.809000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd7e5407726b7'
down_revision = '90478e1df358'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_user_maps',
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], )
    )
    op.drop_constraint(u'video_ibfk_3', 'video', type_='foreignkey')
    op.drop_column(u'video', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'video', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'video_ibfk_3', 'video', 'user', ['user_id'], ['id'])
    op.drop_table('video_user_maps')
    # ### end Alembic commands ###
